name: CI
on:
  push:
  pull_request:

jobs:
  fedora:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: registry.fedoraproject.org/fedora:latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install runtime and test dependencies
        run: dnf install -y openssh-clients python3-mock-ssh-server python3-pytest python3-pytest-asyncio python3-mypy python3-flake8

      - name: Run unit tests
        run: python3 -m pytest

      - name: Run flake8
        run: python3 -m flake8

      - name: Run mypy
        run: python3 -m mypy src/ferny

  c8s:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    container: quay.io/centos/centos:stream8
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install distro runtime and test dependencies
        # we need EPEL for python3-paramiko (required by mock-ssh-server)
        run: |
          dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
          dnf install -y openssh-clients python3-paramiko python3-pip

      # C8S does have python3-pytest, but it's too old for us
      - name: Install pip test dependencies
        run: pip3 install pytest pytest-asyncio mock-ssh-server

      - name: Run unit tests
        run: PYTHONPATH=src python3 -m pytest
