name: toxbox
on:
  pull_request:
jobs:
  venv:
    permissions: {}

    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Run venv tests
        run: test/run --color
